import Head from 'next/head'

import Nav from '../components/nav'
import Header from '../components/header'
import InfoBar from '../components/info'
import Product from '../components/product'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='viewport' content='width=device-width, initial-scale=1' />

        <meta name='description' content='Generated by create next app' />

        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className=' bg-slate-200 mx-1 h-[15vh]'>
        <Nav />
      </div>
      <div className='px-1 '>
        <Header />
      </div>
      <div className='px-1'>
        <InfoBar />
      </div>
      <div className='px-1'>
        <Product />
      </div>
      <div className='px-1 py-1'>
        <Product />
      </div>
    </div>
  )
}
