import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/nav'
import Header from '../components/header'
import InfoBar from '../components/info'
import Product from '../components/product'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='viewport' content='width=device-width, initial-scale=1' />

        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className=' bg-slate-200 mx-2 mt-2  h-[15vh]'>
        <Nav />
      </div>
      <div className='px-2 py-2'>
        <Header />
      </div>
      <div className='px-2 py-1'>
        <InfoBar />
      </div>
      <div className='px-2 py-1'>
        <Product />
      </div>
      <div className='px-2 py-1'>
        <Product />
      </div>
    </div>
  )
}
